import { Product, YarnCategory } from '../types';
import { PRODUCTS_CATALOG } from '../data/products';

let cachedCatalog: Product[] | null = null;
let lastFetchTime = 0;
const CACHE_DURATION_MS = 60 * 1000; // 1 minute in-memory cache

export class ProductService {
  /**
   * Loads product catalog from static /catalog.json with fallback to local PRODUCTS_CATALOG
   */
  static async getCatalog(forceRefresh = false): Promise<Product[]> {
    const now = Date.now();
    if (!forceRefresh && cachedCatalog && now - lastFetchTime < CACHE_DURATION_MS) {
      return cachedCatalog;
    }

    try {
      // Append cache buster to fetch fresh catalog.json generated by static build/deploy
      const response = await fetch(`/catalog.json?v=${now}`, {
        headers: {
          'Accept': 'application/json',
          'Cache-Control': 'no-cache',
        },
      });

      if (!response.ok) {
        throw new Error(`Failed to fetch catalog.json: ${response.status} ${response.statusText}`);
      }

      const rawData = await response.json();
      if (!Array.isArray(rawData)) {
        throw new Error('Catalog data is not an array.');
      }

      // Normalize products & bridge fields (e.g. image -> imageUrl, shade -> default text)
      const normalizedProducts: Product[] = rawData.map((item: any, index: number) => {
        const id = item.id ? String(item.id) : `prod-${index + 1}`;
        const name = item.name || 'Yarn Product';
        const imageResolved = item.image || item.imageUrl || item.photo || '';
        const shadeText = item.shade || item.color || item.shadeNo || 'Standard Mill Shade';

        return {
          ...item,
          id,
          name,
          category: (item.category || 'fancy') as YarnCategory,
          categoryLabel: item.categoryLabel || this.getCategoryLabel(item.category),
          countOrDenier: item.countOrDenier || item.count || item.denier || 'Standard Count',
          description: item.description || 'High quality wholesale yarn from Ved Enterprises Ludhiana.',
          recommendedUses: Array.isArray(item.recommendedUses)
            ? item.recommendedUses
            : typeof item.recommendedUses === 'string'
            ? item.recommendedUses.split(',').map((s: string) => s.trim())
            : ['Knitwear', 'Sweaters', 'Weaving'],
          features: Array.isArray(item.features)
            ? item.features
            : typeof item.features === 'string'
            ? item.features.split(',').map((s: string) => s.trim())
            : ['High Quality', 'Soft Touch', 'Durable'],
          sampleAvailable: item.sampleAvailable !== false,
          origin: item.origin || 'Ved Enterprises Wholesale',
          popularFor: item.popularFor || 'Wholesale Knitwear & Weaving',
          shade: shadeText,
          image: imageResolved,
          imageUrl: imageResolved,
          shadeUrl: item.shadeUrl || item.shadeCardUrl || '',
          pictureUrl: item.pictureUrl || imageResolved || '',
        };
      });

      cachedCatalog = normalizedProducts;
      lastFetchTime = now;
      return normalizedProducts;
    } catch (err) {
      console.warn('[ProductService] Warning loading /catalog.json, falling back to bundled catalog:', err);
      cachedCatalog = PRODUCTS_CATALOG;
      lastFetchTime = now;
      return PRODUCTS_CATALOG;
    }
  }

  /**
   * Fetches a single product by ID
   */
  static async getProductById(id: string): Promise<Product | undefined> {
    const catalog = await this.getCatalog();
    return catalog.find((p) => String(p.id).toLowerCase() === String(id).toLowerCase());
  }

  /**
   * Helper to derive readable category labels
   */
  private static getCategoryLabel(category?: string): string {
    switch (category) {
      case 'china':
        return 'China / Imported Yarn';
      case 'acrylic-blends':
        return 'Acrylic & Blends';
      case 'fabrics':
        return 'Fabrics & Textile Rolls';
      case 'garments':
        return 'Finished Sweaters';
      case 'fancy':
      default:
        return 'Fancy Yarn';
    }
  }
}
